#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Nov  8 08:26:19 2025

@author: paul
"""
from typing import Union

import matplotlib as mpl
import matplotlib.pyplot as plt

from .datamodel.tables import Column, GateGroup
from .photondata import PhotonData, PhotonDataList

from .datamodel.plotting import _get_column_arrays

PhotonDataS = Union[PhotonData, PhotonDataList]


def _time_plotscat(funcstr:str, data:PhotonDataS, col:Column, gate:GateGroup, 
                   ax:plt.Axes, include_unit:bool,
                   xlabel:str, xlabel_kwargs:dict, ylabel:str, ylabel_kwargs:dict, 
                   **kwargs):
    ax = plt.gca() if ax is None else ax
    (yarr,), (name,) = _get_column_arrays(data, col, gate=gate, include_unit=include_unit)
    if include_unit:
        xlabel = 'time (s)' if xlabel is None else xlabel
    else:
        xlabel = 'time' if xlabel is None else xlabel
    ylabel = name if ylabel is None else ylabel
    xarr = data.get_column(col.origin_param.regate(col.gate), 'midtime', ('start', 'stop'))
    out = getattr(ax, funcstr)(xarr, yarr, **kwargs)
    xlbl = ax.set_xlabel(ylabel, **xlabel_kwargs)
    ylbl = ax.set_ylabel(ylabel, **ylabel_kwargs)
    return out, xlbl, ylbl


def time_plot(data:PhotonDataS, col:Column, gate:GateGroup=None, ax:plt.Axes=None, 
              include_unit:bool=False,
              xlabel:str=None, xlabel_kwargs:dict=None,
              ylabel:str=None, ylabel_kwargs:dict=None, 
              **kwargs)->tuple[plt.Line2D,plt.Text,plt.Text]:
    return _time_plotscat('plot', data, col, gate, ax, include_unit, xlabel, xlabel_kwargs, ylabel, ylabel_kwargs, kwargs)


def time_scatter(data:PhotonDataS, col:Column, gate:GateGroup=None, ax:plt.Axes=None, 
                 include_unit:bool=False,
                 xlabel:str=None, xlabel_kwargs:dict=None,
                 ylabel:str=None, ylabel_kwargs:dict=None, 
                 **kwargs)->tuple[mpl.collections.PathCollection,plt.Text,plt.Text]:
    return _time_plotscat('plot', data, col, gate, ax, include_unit, xlabel, xlabel_kwargs, ylabel, ylabel_kwargs, kwargs)